export interface HealthCheckResponse {
  status: string;
}

export const OrgRole = {
  INVITEE: 'INVITEE',
  MEMBER: 'MEMBER',
  MODERATOR: 'MODERATOR',
  OWNER: 'OWNER',
  BANNED: 'BANNED',
} as const;
export type OrgRole = (typeof OrgRole)[keyof typeof OrgRole];

export const FriendshipStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
} as const;
export type FriendshipStatus = (typeof FriendshipStatus)[keyof typeof FriendshipStatus];

export const DogSize = {
  TOY: 'TOY',
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
  GIANT: 'GIANT',
  KAIJU: 'KAIJU',
} as const;
export type DogSize = (typeof DogSize)[keyof typeof DogSize];

export const DogGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;
export type DogGender = (typeof DogGender)[keyof typeof DogGender];

export const DogPlaystyle = {
  SOCIAL: 'SOCIAL',
  SHY: 'SHY',
  AGGRESSIVE: 'AGGRESSIVE',
  ENERGETIC: 'ENERGETIC',
  CALM: 'CALM',
} as const;
export type DogPlaystyle = (typeof DogPlaystyle)[keyof typeof DogPlaystyle];

export const Amenity = {
  WATER_FOUNTAIN: 'WATER_FOUNTAIN',
  SHADE: 'SHADE',
  BENCHES: 'BENCHES',
  WASTE_BAGS: 'WASTE_BAGS',
  OBSTACLES: 'OBSTACLES',
  AGILITY_EQUIPMENT: 'AGILITY_EQUIPMENT',
} as const;
export type Amenity = (typeof Amenity)[keyof typeof Amenity];

export const EventPrivacy = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;
export type EventPrivacy = (typeof EventPrivacy)[keyof typeof EventPrivacy];

export const AchievementType = {
  BADGE: 'BADGE',
  TROPHY: 'TROPHY',
  CERTIFICATE: 'CERTIFICATE',
} as const;
export type AchievementType = (typeof AchievementType)[keyof typeof AchievementType];

export const UserRole = {
  CLIENT: 'CLIENT',
  DEVELOPER: 'DEVELOPER',
  ADMIN: 'ADMIN',
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const MessageStatus = {
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
} as const;
export type MessageStatus = (typeof MessageStatus)[keyof typeof MessageStatus];



export interface User {
  id: number;
  email: string;
  password_hash: string;
  username: string;
  first_name: string | null;
  last_name: string | null;
  profilePictureUrl: string | null;
  resetToken: string | null;
  resetTokenExpiry: string | null;
  latitude: number | null;
  longitude: number | null;
  role: UserRole;
  ExpPoints: number;
  createdAt: string;
  updatedAt: string;
}

export interface Dog {
  id: number;
  name: string;
  breed: DogBreed;
  gender: string;
  fixed: boolean;
  dateOfBirth: string;
  size: DogSize;
  profilePictureUrl: string | null;
  vaccinationRecordUrl: string | null;
  playstyle: DogPlaystyle;
  description: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Friendship {
  id: number;
  requesterId: number | null;
  requesterDogId: number | null;
  addresseeId: number | null;
  addresseeDogId: number | null;
  status: FriendshipStatus;
  createdAt: string;
  updatedAt: string;
}

export interface Messages {
  id: number;
  senderId: number;
  receiverId: number;
  content: string;
  sentAt: string;
  status: MessageStatus;
}

export interface CheckIn {
  id: number;
  userId: number;
  dogId: number | null;
  parkId: number;
  checkedInAt: string;
  checkedOutAt: string | null;
}

export interface Enemies {
  id: number;
  ownerId: number;
  ownerDogId: number | null;
  enemyUserId: number | null;
  enemyDogId: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Park {
  id: number;
  name: string;
  latitude: number;
  longitude: number;
  description: string | null;
  separateSmallDogArea: boolean;
  amenities: Amenity[];
  profilePictureUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface DogOwner {
  userId: number;
  dogId: number;
}

export interface UserFavoritePark {
  userId: number;
  parkId: number;
}

export interface Organization {
  id: number;
  name: string;
  profilePictureUrl: string | null;
  websiteUrl: string | null;
  description: string | null;
  ownerId: number;
  memberRole: OrgRole;
  createdAt: string;
  updatedAt: string;
}

export interface OrganizationMember {
  userId: number;
  organizationId: number;
  role: OrgRole;
  joinedAt: string;
}

export interface Event {
  id: number;
  title: string;
  description: string | null;
  private: EventPrivacy;
  date: string;
  startTime: string;
  endTime: string;
  parkId: number;
  organizationId: number | null;
  organizerId: number;
  createdAt: string;
  updatedAt: string;
}

export interface Comment {
  id: number;
  content: string;
  userId: number;
  parkId: number | null;
  eventId: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Achievements {
  id: number;
  name: string;
  type: AchievementType;
  description: string | null;
  badgeUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface UserAchievement {
  userId: number;
  achievementId: number;
  dateEarned: string;
}

export interface Levels {
  id: number;
  name: string;
  description: string | null;
  minPoints: number;
  maxPoints: number;
  badgeUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface UserLevel {
  userId: number;
  levelId: number;
  dateAchieved: string;
}

export const DogBreed = {
  UNKNOWN: 'UNKNOWN',
  MIXED_BREED: 'MIXED_BREED',
  AFFENPINSCHER: 'AFFENPINSCHER',
  AFGHAN_HOUND: 'AFGHAN_HOUND',
  AIDI: 'AIDI',
  AIREDALE_TERRIER: 'AIREDALE_TERRIER',
  AKBASH: 'AKBASH',
  AKITA: 'AKITA',
  ALANO_ESPANOL: 'ALANO_ESPANOL',
  ALASKAN_MALAMUTE: 'ALASKAN_MALAMUTE',
  ALPENLANDISCHE_DACHSBRACKE: 'ALPENLANDISCHE_DACHSBRACKE',
  AMERICAN_AKITA: 'AMERICAN_AKITA',
  AMERICAN_COCKER_SPANIEL: 'AMERICAN_COCKER_SPANIEL',
  AMERICAN_FOXHOUND: 'AMERICAN_FOXHOUND',
  AMERICAN_STAFFORDSHIRE_TERRIER: 'AMERICAN_STAFFORDSHIRE_TERRIER',
  AMERICAN_WATER_SPANIEL: 'AMERICAN_WATER_SPANIEL',
  ANJING_KINTAMANI_BALI: 'ANJING_KINTAMANI_BALI',
  ANGLO_FRANCAIS_DE_GRANDE_VENERIE: 'ANGLO_FRANCAIS_DE_GRANDE_VENERIE',
  ANGLO_FRANCAIS_DE_MOYENNE_VENERIE: 'ANGLO_FRANCAIS_DE_MOYENNE_VENERIE',
  ANGLO_FRANCAIS_DE_PETITE_VENERIE: 'ANGLO_FRANCAIS_DE_PETITE_VENERIE',
  APPENZELLER_SENNENHUND: 'APPENZELLER_SENNENHUND',
  ARIEGEOIS: 'ARIEGEOIS',
  ARTOIS_HOUND: 'ARTOIS_HOUND',
  AUSTRALIAN_CATTLE_DOG: 'AUSTRALIAN_CATTLE_DOG',
  AUSTRALIAN_KELPIE: 'AUSTRALIAN_KELPIE',
  AUSTRALIAN_SHEPHERD: 'AUSTRALIAN_SHEPHERD',
  AUSTRALIAN_SILKY_TERRIER: 'AUSTRALIAN_SILKY_TERRIER',
  AUSTRALIAN_STUMPY_TAIL_CATTLE_DOG: 'AUSTRALIAN_STUMPY_TAIL_CATTLE_DOG',
  AUSTRALIAN_TERRIER: 'AUSTRALIAN_TERRIER',
  AZAWAKH: 'AZAWAKH',
  BARBET: 'BARBET',
  BASENJI: 'BASENJI',
  BASSET_ARTESIEN_NORMAND: 'BASSET_ARTESIEN_NORMAND',
  BASSET_BLEU_DE_GASCOGNE: 'BASSET_BLEU_DE_GASCOGNE',
  BASSET_FAUVE_DE_BRETAGNE: 'BASSET_FAUVE_DE_BRETAGNE',
  BASSET_HOUND: 'BASSET_HOUND',
  BAVARIAN_MOUNTAIN_SCENT_HOUND: 'BAVARIAN_MOUNTAIN_SCENT_HOUND',
  BEAGLE: 'BEAGLE',
  BEAGLE_HARRIER: 'BEAGLE_HARRIER',
  BEARDED_COLLIE: 'BEARDED_COLLIE',
  BEAUCERON: 'BEAUCERON',
  BEDLINGTON_TERRIER: 'BEDLINGTON_TERRIER',
  BELGIAN_GRIFFON: 'BELGIAN_GRIFFON',
  BELGIAN_SHEPHERD_DOG: 'BELGIAN_SHEPHERD_DOG',
  BERGER_BLANC_SUISSE: 'BERGER_BLANC_SUISSE',
  BERGER_DE_BRIE: 'BERGER_DE_BRIE',
  BERGER_DE_PICARDIE: 'BERGER_DE_PICARDIE',
  BERNESE_MOUNTAIN_DOG: 'BERNESE_MOUNTAIN_DOG',
  BICHON_BOLOGNESE: 'BICHON_BOLOGNESE',
  BICHON_FRISE: 'BICHON_FRISE',
  BLACK_AND_TAN_COONHOUND: 'BLACK_AND_TAN_COONHOUND',
  BLOODHOUND: 'BLOODHOUND',
  BLUE_GASCONY_GRIFFON: 'BLUE_GASCONY_GRIFFON',
  BOHEMIAN_WIRE_HAIRED_POINTING_GRIFFON: 'BOHEMIAN_WIRE_HAIRED_POINTING_GRIFFON',
  BORDER_COLLIE: 'BORDER_COLLIE',
  BORDER_TERRIER: 'BORDER_TERRIER',
  BORZOI: 'BORZOI',
  BOSNIAN_COARSE_HAIRED_HOUND: 'BOSNIAN_COARSE_HAIRED_HOUND',
  BOSTON_TERRIER: 'BOSTON_TERRIER',
  BOUVIER_DES_ARDENNES: 'BOUVIER_DES_ARDENNES',
  BOUVIER_DES_FLANDRES: 'BOUVIER_DES_FLANDRES',
  BOXER: 'BOXER',
  BRACCO_ITALIANO: 'BRACCO_ITALIANO',
  BRAQUE_D_AUVERGNE: 'BRAQUE_D_AUVERGNE',
  BRAQUE_DE_L_ARIEGE: 'BRAQUE_DE_L_ARIEGE',
  BRAQUE_DU_BOURBONNAIS: 'BRAQUE_DU_BOURBONNAIS',
  BRAQUE_FRANCAIS_TYPE_GASCOGNE: 'BRAQUE_FRANCAIS_TYPE_GASCOGNE',
  BRAQUE_FRANCAIS_TYPE_PYRENEES: 'BRAQUE_FRANCAIS_TYPE_PYRENEES',
  BRAZILIAN_TERRIER: 'BRAZILIAN_TERRIER',
  BRIQUET_GRIFFON_VENDEEN: 'BRIQUET_GRIFFON_VENDEEN',
  BROHOLMER: 'BROHOLMER',
  BULL_TERRIER: 'BULL_TERRIER',
  BULLDOG: 'BULLDOG',
  BULLMASTIFF: 'BULLMASTIFF',
  CAIRN_TERRIER: 'CAIRN_TERRIER',
  CANAAN_DOG: 'CANAAN_DOG',
  CANARIAN_WARREN_HOUND: 'CANARIAN_WARREN_HOUND',
  CANE_CORSO_ITALIANO: 'CANE_CORSO_ITALIANO',
  CAO_DA_SERRA_DA_ESTRELA: 'CAO_DA_SERRA_DA_ESTRELA',
  CAO_DA_SERRA_DE_AIRES: 'CAO_DA_SERRA_DE_AIRES',
  CAO_DE_CASTRO_LABOREIRO: 'CAO_DE_CASTRO_LABOREIRO',
  CAO_DE_GADO_TRANSMONTANO: 'CAO_DE_GADO_TRANSMONTANO',
  CAO_FILA_DE_SAO_MIGUEL: 'CAO_FILA_DE_SAO_MIGUEL',
  CATALAN_SHEEPDOG: 'CATALAN_SHEEPDOG',
  CAUCASIAN_SHEPHERD_DOG: 'CAUCASIAN_SHEPHERD_DOG',
  CAVALIER_KING_CHARLES_SPANIEL: 'CAVALIER_KING_CHARLES_SPANIEL',
  CENTRAL_ASIAN_SHEPHERD_DOG: 'CENTRAL_ASIAN_SHEPHERD_DOG',
  CESKY_TERRIER: 'CESKY_TERRIER',
  CHESAPEAKE_BAY_RETRIEVER: 'CHESAPEAKE_BAY_RETRIEVER',
  CHIHUAHUA: 'CHIHUAHUA',
  CHINESE_CRESTED_DOG: 'CHINESE_CRESTED_DOG',
  CHODSKY_PES: 'CHODSKY_PES',
  CHOW_CHOW: 'CHOW_CHOW',
  CIRNECO_DELL_ETNA: 'CIRNECO_DELL_ETNA',
  CLUMBER_SPANIEL: 'CLUMBER_SPANIEL',
  COCKER_SPANIEL: 'COCKER_SPANIEL',
  COLLIE_ROUGH: 'COLLIE_ROUGH',
  COLLIE_SMOOTH: 'COLLIE_SMOOTH',
  CONTINENTAL_BULLDOG: 'CONTINENTAL_BULLDOG',
  COTON_DE_TULEAR: 'COTON_DE_TULEAR',
  CROATIAN_SHEEPDOG: 'CROATIAN_SHEEPDOG',
  CURLY_COATED_RETRIEVER: 'CURLY_COATED_RETRIEVER',
  DACHSHUND: 'DACHSHUND',
  DALMATIAN: 'DALMATIAN',
  DANDIE_DINMONT_TERRIER: 'DANDIE_DINMONT_TERRIER',
  DANISH_SWEDISH_FARMDOG: 'DANISH_SWEDISH_FARMDOG',
  DEERHOUND: 'DEERHOUND',
  DOBERMANN: 'DOBERMANN',
  DOGO_ARGENTINO: 'DOGO_ARGENTINO',
  DOGUE_DE_BORDEAUX: 'DOGUE_DE_BORDEAUX',
  DRENTSCHE_PATRIJSHOND: 'DRENTSCHE_PATRIJSHOND',
  DREVER: 'DREVER',
  DUNKER: 'DUNKER',
  DUTCH_SCHAPENDOES: 'DUTCH_SCHAPENDOES',
  DUTCH_SHEPHERD_DOG: 'DUTCH_SHEPHERD_DOG',
  EAST_SIBERIAN_LAIKA: 'EAST_SIBERIAN_LAIKA',
  ENGLISH_COCKER_SPANIEL: 'ENGLISH_COCKER_SPANIEL',
  ENGLISH_FOXHOUND: 'ENGLISH_FOXHOUND',
  ENGLISH_POINTER: 'ENGLISH_POINTER',
  ENGLISH_SETTER: 'ENGLISH_SETTER',
  ENGLISH_SPRINGER_SPANIEL: 'ENGLISH_SPRINGER_SPANIEL',
  ENGLISH_TOY_TERRIER: 'ENGLISH_TOY_TERRIER',
  ENTLEBUCHER_MOUNTAIN_DOG: 'ENTLEBUCHER_MOUNTAIN_DOG',
  EPAGNEUL_BLEU_DE_PICARDIE: 'EPAGNEUL_BLEU_DE_PICARDIE',
  EPAGNEUL_BRETON: 'EPAGNEUL_BRETON',
  EPAGNEUL_FRANCAIS: 'EPAGNEUL_FRANCAIS',
  EPAGNEUL_PICARD: 'EPAGNEUL_PICARD',
  ESTONIAN_HOUND: 'ESTONIAN_HOUND',
  EURASIER: 'EURASIER',
  FIELD_SPANIEL: 'FIELD_SPANIEL',
  FILA_BRASILEIRO: 'FILA_BRASILEIRO',
  FINNISH_HOUND: 'FINNISH_HOUND',
  FINNISH_LAPPHUND: 'FINNISH_LAPPHUND',
  FINNISH_SPITZ: 'FINNISH_SPITZ',
  FLAT_COATED_RETRIEVER: 'FLAT_COATED_RETRIEVER',
  FOX_TERRIER_SMOOTH: 'FOX_TERRIER_SMOOTH',
  FOX_TERRIER_WIRE: 'FOX_TERRIER_WIRE',
  FRENCH_BULLDOG: 'FRENCH_BULLDOG',
  GALGO_ESPANOL: 'GALGO_ESPANOL',
  GASCON_SAINTONGEOIS: 'GASCON_SAINTONGEOIS',
  GERMAN_HOUND: 'GERMAN_HOUND',
  GERMAN_PINSCHER: 'GERMAN_PINSCHER',
  GERMAN_SHEPHERD_DOG: 'GERMAN_SHEPHERD_DOG',
  GERMAN_SHORT_HAIRED_POINTER: 'GERMAN_SHORT_HAIRED_POINTER',
  GERMAN_SPITZ: 'GERMAN_SPITZ',
  GERMAN_WIRE_HAIRED_POINTER: 'GERMAN_WIRE_HAIRED_POINTER',
  GIANT_SCHNAUZER: 'GIANT_SCHNAUZER',
  GLEN_OF_IMAAL_TERRIER: 'GLEN_OF_IMAAL_TERRIER',
  GOLDEN_RETRIEVER: 'GOLDEN_RETRIEVER',
  GORDON_SETTER: 'GORDON_SETTER',
  GRAND_BASSET_GRIFFON_VENDEEN: 'GRAND_BASSET_GRIFFON_VENDEEN',
  GRAND_BLEU_DE_GASCOGNE: 'GRAND_BLEU_DE_GASCOGNE',
  GRAND_GRIFFON_VENDEEN: 'GRAND_GRIFFON_VENDEEN',
  GREAT_DANE: 'GREAT_DANE',
  GREAT_PYRENEES: 'GREAT_PYRENEES',
  GREATER_SWISS_MOUNTAIN_DOG: 'GREATER_SWISS_MOUNTAIN_DOG',
  GREENLAND_DOG: 'GREENLAND_DOG',
  GREYHOUND: 'GREYHOUND',
  HALDEN_HOUND: 'HALDEN_HOUND',
  HAMILTONSTOVARE: 'HAMILTONSTOVARE',
  HANOVERIAN_SCENT_HOUND: 'HANOVERIAN_SCENT_HOUND',
  HARRIER: 'HARRIER',
  HAVANESE: 'HAVANESE',
  HOKKAIDO: 'HOKKAIDO',
  HOVAWART: 'HOVAWART',
  IBIZAN_HOUND: 'IBIZAN_HOUND',
  ICELANDIC_SHEEPDOG: 'ICELANDIC_SHEEPDOG',
  IRISH_GLEN_OF_IMAAL_TERRIER: 'IRISH_GLEN_OF_IMAAL_TERRIER',
  IRISH_RED_AND_WHITE_SETTER: 'IRISH_RED_AND_WHITE_SETTER',
  IRISH_SETTER: 'IRISH_SETTER',
  IRISH_TERRIER: 'IRISH_TERRIER',
  IRISH_WATER_SPANIEL: 'IRISH_WATER_SPANIEL',
  IRISH_WOLFHOUND: 'IRISH_WOLFHOUND',
  ISTRIAN_COARSE_HAIRED_HOUND: 'ISTRIAN_COARSE_HAIRED_HOUND',
  ISTRIAN_SHORT_HAIRED_HOUND: 'ISTRIAN_SHORT_HAIRED_HOUND',
  ITALIAN_GREYHOUND: 'ITALIAN_GREYHOUND',
  JACK_RUSSELL_TERRIER: 'JACK_RUSSELL_TERRIER',
  JAPANESE_CHIN: 'JAPANESE_CHIN',
  JAPANESE_SPITZ: 'JAPANESE_SPITZ',
  JINDO: 'JINDO',
  KAI: 'KAI',
  KANGAL_SHEPHERD_DOG: 'KANGAL_SHEPHERD_DOG',
  KARELIAN_BEAR_DOG: 'KARELIAN_BEAR_DOG',
  KAZAKH_TAZY: 'KAZAKH_TAZY',
  KEESHOND: 'KEESHOND',
  KERRY_BLUE_TERRIER: 'KERRY_BLUE_TERRIER',
  KING_CHARLES_SPANIEL: 'KING_CHARLES_SPANIEL',
  KOMONDOR: 'KOMONDOR',
  KOREAN_JINDO_DOG: 'KOREAN_JINDO_DOG',
  KROMFOHRLANDER: 'KROMFOHRLANDER',
  KUVASZ: 'KUVASZ',
  LABRADOR_RETRIEVER: 'LABRADOR_RETRIEVER',
  LAGOTTO_ROMAGNOLO: 'LAGOTTO_ROMAGNOLO',
  LAKELAND_TERRIER: 'LAKELAND_TERRIER',
  LANCASHIRE_HEELER: 'LANCASHIRE_HEELER',
  LAPINPOROKOIRA: 'LAPINPOROKOIRA',
  LEONBERGER: 'LEONBERGER',
  LHASA_APSO: 'LHASA_APSO',
  LITTLE_LION_DOG: 'LITTLE_LION_DOG',
  MAJORCA_SHEPHERD_DOG: 'MAJORCA_SHEPHERD_DOG',
  MALTESE: 'MALTESE',
  MANCHESTER_TERRIER: 'MANCHESTER_TERRIER',
  MAREMMA_AND_THE_ABRUZZES_SHEEPDOG: 'MAREMMA_AND_THE_ABRUZZES_SHEEPDOG',
  MASTIFF: 'MASTIFF',
  MINIATURE_AMERICAN_SHEPHERD: 'MINIATURE_AMERICAN_SHEPHERD',
  MINIATURE_BULL_TERRIER: 'MINIATURE_BULL_TERRIER',
  MINIATURE_PINSCHER: 'MINIATURE_PINSCHER',
  MINIATURE_SCHNAUZER: 'MINIATURE_SCHNAUZER',
  MUDI: 'MUDI',
  NEAPOLITAN_MASTIFF: 'NEAPOLITAN_MASTIFF',
  NEWFOUNDLAND: 'NEWFOUNDLAND',
  NORFOLK_TERRIER: 'NORFOLK_TERRIER',
  NORRBOTTENSPITZ: 'NORRBOTTENSPITZ',
  NORWEGIAN_BUHUND: 'NORWEGIAN_BUHUND',
  NORWEGIAN_ELKHOUND_BLACK: 'NORWEGIAN_ELKHOUND_BLACK',
  NORWEGIAN_ELKHOUND_GREY: 'NORWEGIAN_ELKHOUND_GREY',
  NORWEGIAN_HOUND: 'NORWEGIAN_HOUND',
  NORWICH_TERRIER: 'NORWICH_TERRIER',
  NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER: 'NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER',
  OLD_DANISH_POINTER: 'OLD_DANISH_POINTER',
  OLD_ENGLISH_SHEEPDOG: 'OLD_ENGLISH_SHEEPDOG',
  OTTERHOUND: 'OTTERHOUND',
  PARSON_RUSSELL_TERRIER: 'PARSON_RUSSELL_TERRIER',
  PEKINGESE: 'PEKINGESE',
  PERRO_DE_AGUA_ESPANOL: 'PERRO_DE_AGUA_ESPANOL',
  PERRO_SIN_PELO_DEL_PERU: 'PERRO_SIN_PELO_DEL_PERU',
  PHARAOH_HOUND: 'PHARAOH_HOUND',
  PICARDY_SHEEPDOG: 'PICARDY_SHEEPDOG',
  PODENGO_PORTUGUES: 'PODENGO_PORTUGUES',
  POLISH_GREYHOUND: 'POLISH_GREYHOUND',
  POLISH_HOUND: 'POLISH_HOUND',
  POLISH_HUNTING_DOG: 'POLISH_HUNTING_DOG',
  POLISH_LOWLAND_SHEEPDOG: 'POLISH_LOWLAND_SHEEPDOG',
  POMERANIAN: 'POMERANIAN',
  PRESA_CANARIO: 'PRESA_CANARIO',
  PUDELPOINTER: 'PUDELPOINTER',
  PUG: 'PUG',
  PULI: 'PULI',
  PUMI: 'PUMI',
  PYRENEAN_MASTIFF: 'PYRENEAN_MASTIFF',
  PYRENEAN_SHEEPDOG: 'PYRENEAN_SHEEPDOG',
  RHODESIAN_RIDGEBACK: 'RHODESIAN_RIDGEBACK',
  ROMANIAN_BUCOVINA_SHEPHERD: 'ROMANIAN_BUCOVINA_SHEPHERD',
  ROMANIAN_CARPATHIAN_SHEPHERD_DOG: 'ROMANIAN_CARPATHIAN_SHEPHERD_DOG',
  ROMANIAN_MIORITIC_SHEPHERD_DOG: 'ROMANIAN_MIORITIC_SHEPHERD_DOG',
  ROMANIAN_RAVEN_SHEPHERD_DOG: 'ROMANIAN_RAVEN_SHEPHERD_DOG',
  ROTTWEILER: 'ROTTWEILER',
  RUSSIAN_BLACK_TERRIER: 'RUSSIAN_BLACK_TERRIER',
  RUSSIAN_TOY: 'RUSSIAN_TOY',
  SAARLOOS_WOLFDOG: 'SAARLOOS_WOLFDOG',
  SAINT_BERNARD: 'SAINT_BERNARD',
  SAINT_GERMAIN_POINTER: 'SAINT_GERMAIN_POINTER',
  SALUKI: 'SALUKI',
  SAMOYED: 'SAMOYED',
  SCHIPPERKE: 'SCHIPPERKE',
  SCHNAUZER: 'SCHNAUZER',
  SCOTTISH_TERRIER: 'SCOTTISH_TERRIER',
  SEALYHAM_TERRIER: 'SEALYHAM_TERRIER',
  SEGUGIO_ITALIANO: 'SEGUGIO_ITALIANO',
  SEGUGIO_MAREMMANO: 'SEGUGIO_MAREMMANO',
  SERBIAN_HOUND: 'SERBIAN_HOUND',
  SERBIAN_TRICOLOUR_HOUND: 'SERBIAN_TRICOLOUR_HOUND',
  SHAR_PEI: 'SHAR_PEI',
  SHETLAND_SHEEPDOG: 'SHETLAND_SHEEPDOG',
  SHIBA: 'SHIBA',
  SHIH_TZU: 'SHIH_TZU',
  SIBERIAN_HUSKY: 'SIBERIAN_HUSKY',
  SLOUGHI: 'SLOUGHI',
  SLOVAKIAN_CHUVACH: 'SLOVAKIAN_CHUVACH',
  SLOVAKIAN_HOUND: 'SLOVAKIAN_HOUND',
  SLOVAKIAN_WIRE_HAIRED_POINTER: 'SLOVAKIAN_WIRE_HAIRED_POINTER',
  SMALL_MUNSTERLANDER: 'SMALL_MUNSTERLANDER',
  SOUTH_RUSSIAN_SHEPHERD_DOG: 'SOUTH_RUSSIAN_SHEPHERD_DOG',
  SPANISH_MASTIFF: 'SPANISH_MASTIFF',
  SPANISH_WATER_DOG: 'SPANISH_WATER_DOG',
  SPINONE_ITALIANO: 'SPINONE_ITALIANO',
  STABIJHOUN: 'STABIJHOUN',
  STAFFORDSHIRE_BULL_TERRIER: 'STAFFORDSHIRE_BULL_TERRIER',
  SUSSEX_SPANIEL: 'SUSSEX_SPANIEL',
  SWEDISH_LAPPHUND: 'SWEDISH_LAPPHUND',
  SWEDISH_VALLHUND: 'SWEDISH_VALLHUND',
  TAIWAN_DOG: 'TAIWAN_DOG',
  TATRA_SHEPHERD_DOG: 'TATRA_SHEPHERD_DOG',
  THAI_BANGKAEW_DOG: 'THAI_BANGKAEW_DOG',
  THAI_RIDGEBACK_DOG: 'THAI_RIDGEBACK_DOG',
  TIBETAN_MASTIFF: 'TIBETAN_MASTIFF',
  TIBETAN_SPANIEL: 'TIBETAN_SPANIEL',
  TIBETAN_TERRIER: 'TIBETAN_TERRIER',
  TORNJAK: 'TORNJAK',
  TOSA: 'TOSA',
  VALENCIAN_RAT_HUNTING_DOG: 'VALENCIAN_RAT_HUNTING_DOG',
  VASTGOTASPETS: 'VASTGOTASPETS',
  VOLPINO_ITALIANO: 'VOLPINO_ITALIANO',
  WEIMARANER: 'WEIMARANER',
  WELSH_CORGI_CARDIGAN: 'WELSH_CORGI_CARDIGAN',
  WELSH_CORGI_PEMBROKE: 'WELSH_CORGI_PEMBROKE',
  WELSH_SPRINGER_SPANIEL: 'WELSH_SPRINGER_SPANIEL',
  WEST_HIGHLAND_WHITE_TERRIER: 'WEST_HIGHLAND_WHITE_TERRIER',
  WEST_SIBERIAN_LAIKA: 'WEST_SIBERIAN_LAIKA',
  WHIPPET: 'WHIPPET',
  WHITE_SWISS_SHEPHERD_DOG: 'WHITE_SWISS_SHEPHERD_DOG',
  WIREHAIRED_SLOVAKIAN_POINTER: 'WIREHAIRED_SLOVAKIAN_POINTER',
  XOLOITZCUINTLE: 'XOLOITZCUINTLE',
  YAKUTIAN_LAIKA: 'YAKUTIAN_LAIKA',
  YORKSHIRE_TERRIER: 'YORKSHIRE_TERRIER',
} as const;
export type DogBreed = (typeof DogBreed)[keyof typeof DogBreed];